spring:
  application:
    name: turbineServer

server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
    healthcheck:
      enabled: true
  instance:
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 20

turbine:
  app-config: jerryService,tomService
  aggregator:
    clusterConfig: default
  cluster-name-expression: new String("default")
  combine-host-port: true