spring:
  application:
    name: zuul-server

server:
  port: 8081

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/

zuul:
  host:
    maxTotalConnections: 200
    maxPerRouteConnections: 20
  ignoredServices: '*'
  routes:
    mindMap:
      path: /mindMap/**
      serviceId: mindMap-service
