spring:
  application:
    name: zuulServer

server:
  port: 8080

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/

zuul:
  host:
    maxTotalConnections: 200
    maxPerRouteConnections: 20
  ignoredServices: '*'
  routes:
    tom:
      path: /tom/**
      serviceId: tomService
    jerry:
      path: /jerry/**
      serviceId: jerryService
