eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.31.201:8761/eureka/,http://192.168.31.201:8762/eureka/
---
server:
  port: 8761
spring:
  profiles: peer1
eureka:
  instance:
    preferIpAddress: true

---
server:
  port: 8762
spring:
  profiles: peer2
eureka:
  instance:
    preferIpAddress: true