eureka:
  server:
#    enable-self-preservation: false
#    renewal-percent-threshold: 0
    evictionIntervalTimerInMs : 20000
    wait-time-in-ms-when-sync-empt: 60*1000
  instance:
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 20
---
spring:
  profiles: peer1
server:
  port: 8761
eureka:
  instance:
#    preferIpAddress: true
    hostname: eureka-peer1
  client:
    serviceUrl:
      defaultZone: http://eureka-peer2:8762/eureka/

---
spring:
  profiles: peer2
server:
  port: 8762
eureka:
  instance:
#    preferIpAddress: true
    hostname: eureka-peer2
  client:
    serviceUrl:
      defaultZone: http://eureka-peer1:8761/eureka/