server:
  port: 8101

sayYeah: "Yeah, I`m jerry"

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream,info,health
