eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
    healthcheck:
      enabled: true
  instance:
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 20

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream,info,health

circuitBreaker:
  requestVolumeThreshold: 2
  errorThresholdPercentage: 50
metrics:
  rollingStats:
    timeInMilliseconds: 5000

---
spring:
  profiles: a

server:
  port: 8102

sayYeah: "Yeah, I`m jerry a"

---
spring:
  profiles: b

server:
  port: 8103

sayYeah: "Yeah, I`m jerry b"


