spring:
  application:
    name: eureka-admin-server

server:
  port: 8080

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:${server.port}/eureka/
#  instance:
#    hostname: localhost
#    statusPageUrl: https://${eureka.instance.hostname}/info
#    healthCheckUrl: https://${eureka.instance.hostname}/health
#    homePageUrl: https://${eureka.instance.hostname}/