spring:
  application:
    name: mindMap-service

server:
  port: 8082

eureka:
  instance:
    preferIpAddress: true
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/